[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "vite"
  targetPort = 5173
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions."lock-period"]
  schedule = "0 5 * * *"

[functions."reminder-cron"]
  schedule = "0 14 * * 5"
